### PR TITLE
Add keywords option

### PR DESCRIPTION
**Pull request by baptisteArno**
See #1

### CODE REVIEW

**Comment by baptisteArno** [comment]
This is a draft, I'm taking a Christmas break as well 😃

**Comment by baptisteArno** [comment]
Everything works fine. I'm struggling with translation, I'll let you take a look if your OK 👍

**Comment by leodr** [comment]
> Everything works fine. I'm struggling with translation, I'll let you take a look if your OK 👍

I'll have a look at it on 27th or 28th. Happy holidays till then!

**Comment by baptisteArno** [comment]
Thanks man, you too! Cheers

**Comment by baptisteArno** [comment]
Did you have time to check this draft @leodr?

**Comment by leodr** [comment]
I don’t really have any time for this right now, maybe you can just work with your fork for now, since there is not much happening here upstream anyways.

**Pull request closed without merging**
